### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by illeng** [tmiland/GNU-IceCat#1]
![Screenshot_2021-04-10_03-33-13](https://user-images.githubusercontent.com/76645611/114262495-cb1eb780-99cf-11eb-9ede-ee5c755395ff.png)
After successfully installing on a Zorin OS Lite, it works perfectly, but the only problem is it doesn't have icons.

**Comment by tmiland** [comment]
Hi, did you run `sudo apt-get install menu`?

**Comment by tmiland** [comment]
I have updated the repo with a new package, see info: [install-on-debianubuntu](https://github.com/tmiland/GNU-IceCat#install-on-debianubuntu)

**Comment by illeng** [comment]
Thanks for the update
