### ISSUE TITLE
Login form is not shown at gitlab.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [tmiland/GNU-IceCat#3]
**Steps to reproduce:**
1. Navigate to: https://gitlab.com/users/sign_in
2. Observe the page.

**Expected Behavior:**
The login form is shown.

**Actual Behavior:**
The page is blank.

**Tested with:**
Browser / Version: Icecat Mobile 68.0
Operating System: Android 12

**Notes:**

1. Not reproducible on the latest build of Firefox Nightly.
2. Screenshot attached:

![Screenshot_14](https://user-images.githubusercontent.com/75027050/168596227-240bd94f-a494-4659-a8e0-eff46297437d.png)

**Comment by softvision-raul-bucata** [comment]
This is an issue for Android-based devices, but a similar repo could not be found. If possible, I will gladly re-submit this issue to the correct place, if redirection is offered.

**Comment by tmiland** [comment]
Hello,

please direct bug-reports to [bug-gnuzilla](https://lists.gnu.org/mailman/listinfo/bug-gnuzilla)

Thanks.
