### ISSUE TITLE
Page keeps reloading at users.nexusmods.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [tmiland/GNU-IceCat#5]
**URL**: https://users.nexusmods.com/auth/sign_in

**Browser / Version**: Firefox 102.0
**Operating System**: Linux
**Tested Another Browser**: No 

**Problem type**: Site is not usable
**Description**: Unable to login
**Steps to Reproduce**:
https://users.nexusmods.com/auth/sign_in This page appears to keep reloading itself on GNU Icecat 102.4.0esr (64-bit) in Troubleshoot mode. Troubleshoot mode disables all browser extensions and customization's. I cannot log into the website if the Cloudflare operated authentication page does not work on GNU Icecat! I tried looking for help thoroughly on Cloudflares' help website to no avail. 
<details>
      <summary>View the screenshot</summary>
      <img alt="Screenshot" src="https://webcompat.com/uploads/2022/11/01d7cf00-b6ce-4c24-a820-8d818474f085.jpeg">
      </details>

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>gfx.webrender.all: false</li><li>gfx.webrender.blob-images: true</li><li>gfx.webrender.enabled: false</li><li>image.mem.shared: true</li><li>buildID: 20221102222502</li><li>channel: default</li><li>hasTouchScreen: false</li><li>mixed active content blocked: false</li><li>mixed passive content blocked: false</li><li>tracking content blocked: false</li>
</ul>
</details>

[View console log messages](https://webcompat.com/console_logs/2022/11/0d42d55b-50e0-4132-a3f5-1c29a72183ea)

Originally posted here: https://github.com/webcompat/web-bugs/issues/113647

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by softvision-raul-bucata** [comment]
We appreciate your report. I have moved the issue to the relevant project. Please see: https://github.com/tmiland/GNU-IceCat/issues/5

[qa_45/2022]

**Comment by tmiland** [comment]
Hello,

please direct bug-reports to [bug-gnuzilla](https://lists.gnu.org/mailman/listinfo/bug-gnuzilla)

Thanks.
